# Generated by Django 2.1.7 on 2019-03-16 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admin',
            fields=[
                ('admin_id', models.IntegerField(primary_key=True, serialize=False)),
                ('admin_username', models.CharField(max_length=20)),
                ('admin_pwd', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='amenity',
            fields=[
                ('amenity_id', models.IntegerField(primary_key=True, serialize=False)),
                ('amenity_type', models.CharField(max_length=30)),
                ('amenity_capacity', models.CharField(max_length=30, null=True)),
                ('amenity_status', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='rent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent_fee', models.FloatField(default=0.0)),
                ('utility_fee', models.FloatField(default=0.0)),
                ('movein_date', models.DateField(null=True)),
                ('moveout_date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='renter',
            fields=[
                ('renter_id', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=50)),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=10, null=True)),
                ('renter_pwd', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=20)),
                ('carplate', models.CharField(max_length=20, null=True)),
                ('blance', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(null=True)),
                ('end_time', models.DateTimeField(null=True)),
                ('Amenity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='housing.amenity')),
                ('Renter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='housing.renter')),
            ],
        ),
        migrations.CreateModel(
            name='room',
            fields=[
                ('room_number', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('room_type', models.CharField(max_length=5)),
                ('room_description', models.CharField(max_length=500, null=True)),
                ('room_status', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='rent',
            name='renter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='housing.renter'),
        ),
        migrations.AddField(
            model_name='rent',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='housing.room'),
        ),
    ]
